### ISSUE TITLE
Replica (active-active-active) INCR

### ISSUE THREAD

**Issue by mbfdias** [EQ-Alpha/KeyDB#111] opened 2019-11-22 02:51 UTC
On KeyDb-unstable branch 64 bit with persistence (using the same config of #83) on nodes A:6379 B:6380 C:6381 using localhost for demo purposes using the most basic config

#STEP 1 check if mycounter exists
for a in 6379 6380 6381; do redis-cli -a mypassword123 -p $a GET mycounter; done
(nil)
(nil)
(nil)

#STEP 2 mass increment mycounter 
for b in {1..10000}; do for a in 6379 6380 6381; do redis-cli -a mypassword123 -p $a INCR mycounter; done; done

#STEP 2a stop one of the nodes and start it up again a few seconds later while the mass increment is still running 
redis-cli -a mypassword123 -p 6381 shutdown
keydb-server C.conf

#STEP 3 check if mycounter is the same on all 3 nodes... 
for a in 6379 6380 6381; do redis-cli -a mypassword123 -p $a GET mycounter; done
"26359"
"26359"
"17163"

and it is not. If I wait until the end of mass increment to restart the downed server, everything is fine and all 3 nodes return the same. It's just if the server is restarted in the middle of the run, which leads to this inconsistency.

**Comment by JohnSully** [comment] 2019-11-22 05:53
Hmm. I wonder if the REPL backlog is overflowing while the RDB is transferred.

**Comment by JohnSully** [comment] 2019-11-22 19:40
Appears to be multi-master specific.  Can't repro with normal Active Replication.

**Comment by JohnSully** [comment] 2020-03-26 02:07
This cannot be fixed without implementing CRDTs for this datatype.  INCR is a natural candidate for it so this shouldn't be too difficult.

**Comment by 0xFate** [comment] 2020-10-30 12:48
this also holds true for active replication w/ 3 nodes in ring setup, unless "replica-serve-stale-data no" is set, and for bigger rings 4+ even w/ this setting, for partly obvious reasons (split brain). perhaps we should strongly discourage such setups in active-replication docs as mentioning split brain handling may suggest otherwise?
(if you cant reproduce please send me a bump)

**Comment by VivekSainiEQ** [comment] 2021-08-18 20:25
Since RAFT is an active work in progress, and would fix this issue as well as CRDTs would, closing this issue and tracking with #349 instead.

**Closed by VivekSainiEQ** 2021-08-18 20:25 UTC
Labels: bug, multi-master
