### ISSUE TITLE
[BUG] Errors in multi-master node to get replica

### ISSUE THREAD

**Issue by JarmoSa** [EQ-Alpha/KeyDB#319] opened 2021-05-31 13:12 UTC
**Describe the bug**

We are trying to setup Keydb as 4 node multi-master setup between two datacenters for disaster recovery.
Nodes trying to get the replica from master are producing errors 
== CRITICAL == This replica is sending an error to its master: ‘Invalid MVCC Tstamp’ after processing the command ‘KEYDB.MVCCRESTORE’
Latest backlog is: ‘“b4-46fd-819b-a879a588c46d\r\n$153\r\n*5\r\n$17\r\nKEYDB.MVCCRESTORE\r\n$44\r\nmyvine:STAT:C271F2F6588DD73BE0530502020A5897\r\n$20\r\n18446744073709551615\r\n$13\r\n1626350182830\r\n$20\r\n\x00\b18763:10\t\x00H\xda\x1a\xd4\xcbZ\xd0\xa1\r\n\r\n$1\r\n0\r\n$19\r\n1700941248263623573\r\n\r\n$1\r\n0\r\n$19\r\n1700941309739532331\r\n”’

Sending these errors between the nodes and to push these to kibana will also cause the network to oversaturate and cause connections to clients to break => the nodes will bounce up and down and the clients will loose connections.

**To reproduce**

1. We have about 3GB data in Redis. One master, two replicas
2. We convert the replica nodes from redis to keydb, the master is still Redis
3. Take master Redis offline => Sentinel will make one of the keydb nodes master
4. upgrade last Redis to KeyDB
5. Take all other nodes offline but the one master
6. Change the config files to default keyDB + to multi-master
7. take first multi-master node online
=> errors are logged and the whole system bounces up and down

The more nodes I try to add, the worse the situation will get. It is possible to get two multi-master nodes online after waiting few hours for the situation to stabilise, but I cannot get the thirds node online + the unavailability of KeyDB will make it impossible to wait for long time.

**Expected behavior**

No error logging + the missing timestamp should be added on suitable place

**Additional information**

Investigated a bit of the Redis source code vs Keydb. Looks like Redis does not use timestamps at all

So maybe the problem is simply this:
the RDB file is from Redis and does not have timestamps and KeyDB is streaming it to new node which then complains about this

And solution would be
a) ignore the missing timestamp in initial replicaof-load in replica and just add new timestamp?
b) add the missing timestamp during the streaming from master

I guess the b) would be better so that the timestamps would be the same in both.

**Comment by Patrick-Remy** [comment] 2021-06-08 13:05
We have trouble with the same error, even when doing a `FLUSHALL` before starting the second node. In both multi-master and master-master modes (2 vs. 3 nodes).

**Comment by baldugus** [comment] 2021-08-11 22:04
I've got this problem setting up a master-master today but it was a fresh install (not a Redis before). I'm running KeyDB v6.0.18.

It seemed to happen after i configured ACLs for replication, but it might be a coincidence. Any clues on what causes this?

I might try a fresh install again and try to reproduce it later.

**Comment by VivekSainiEQ** [comment] 2021-08-11 22:18
Hi all.

The 'Invalid MVCC Tstamp' error was due to a bug where we were interpreting the MVCC_INVALID code incorrectly when attempting to restore it (The MVCC_INVALID timestamp exists if a key was written by either Redis or KeyDB without active replication enabled). This has been fixed with #334 which is slated to be included in the next release.

In addition, if you're noticing KeyDB specifically is killing connections and causing up and down behaviour, it may be tied to the `client-output-buffer-limit replica` being set too low (similar to #309). In that case, you can try increasing them past the default, or even setting it to "0 0 0" to remove the limits entirely.

**Comment by VivekSainiEQ** [comment] 2021-08-16 15:40
Hi again all,

The fix has been included with the release of v6.2.0, you should now no longer have your logs flooded with Invalid 'MVCC Tstamp errors' upon loading in a Redis .rdb file while in active-replication mode.

**Closed by VivekSainiEQ** 2021-08-16 15:40 UTC
