### ISSUE TITLE
KeyDB Pro Dropping Connections

### ISSUE THREAD

**Issue by eni9889** [EQ-Alpha/KeyDB#185] opened 2020-05-20 18:34 UTC
**Describe the bug**
I am randomly getting connection refused errors. There are no errors in the logs. 

I also tried to run the benchmark and am getting multiple connections dropped messages.

I am running the keydb-server on AWS on an m5.large instance.

** Log Files **

From benchmark
```
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
connection dropped.s]  4 threads:      375000 ops,   12606 (avg:   14290) ops/sec, 641.32KB/sec (avg: 730.10KB/sec), 770.23 (avg: 490.84) msec latency
connection dropped.s]  4 threads:      433700 ops,   15663 (avg:   14332) ops/sec, 800.48KB/sec (avg: 732.19KB/sec), 573.38 (avg: 501.37) msec latency
connection dropped.s]  4 threads:      567980 ops,   12270 (avg:   14454) ops/sec, 626.79KB/sec (avg: 738.21KB/sec), 615.59 (avg: 507.56) msec latency
connection dropped.s]  4 threads:      632800 ops,   13552 (avg:   14291) ops/sec, 691.05KB/sec (avg: 729.82KB/sec), 553.69 (avg: 514.05) msec latency
connection dropped.cs]  4 threads:      851480 ops,   11924 (avg:   14113) ops/sec, 608.50KB/sec (avg: 720.54KB/sec), 637.25 (avg: 528.49) msec latency
connection dropped.cs]  4 threads:      865480 ops,   13949 (avg:   14110) ops/sec, 712.76KB/sec (avg: 720.41KB/sec), 558.80 (avg: 528.98) msec latency
```

Keydb Logs:
```
4459:4470:M 20 May 2020 18:33:06.929 - Accepted 172.31.21.213:55614
4459:4469:M 20 May 2020 18:33:09.256 - Reading from client: Connection reset by peer
4459:4470:M 20 May 2020 18:33:09.256 - Reading from client: Connection reset by peer
4459:4470:M 20 May 2020 18:33:09.256 - Reading from client: Connection reset by peer
4459:4470:M 20 May 2020 18:33:09.256 - Reading from client: Connection reset by peer
4459:4470:M 20 May 2020 18:33:09.256 - Reading from client: Connection reset by peer
4459:4469:M 20 May 2020 18:33:09.257 - Reading from client: Connection reset by peer
4459:4469:M 20 May 2020 18:33:09.257 - Reading from client: Connection reset by peer
4459:4469:M 20 May 2020 18:33:09.257 - Reading from client: Connection reset by peer
```

Please copy everything after this line.

**To Reproduce**
I'm not sure how to reproduce this. I am using the latest version of KeyDB

***Update**
It looks like the benchmark runs fine when I run it locally, but attempting to connect to the instance from a separate server

**Comment by eni9889** [comment] 2020-05-20 18:57
It looks like if I run the benchmarks on the server itself things are fine but when connecting remotely I'm getting this:

```
RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
Connection error: Operation timed out  1579460 ops,   14762 (avg:   14363) ops/sec, 2.36MB/sec (avg: 2.30MB/sec), 401.03 (avg: 452.98) msec latencyy
Connection error: Operation timed out  1594030 ops,   14514 (avg:   14364) ops/sec, 2.32MB/sec (avg: 2.30MB/sec), 669.10 (avg: 454.95) msec latency
Connection error: Operation timed out  1608573 ops,   14480 (avg:   14365) ops/sec, 2.32MB/sec (avg: 2.30MB/sec), 565.20 (avg: 455.95) msec latency
connection dropped.cs]  4 threads:     1722263 ops,   14476 (avg:   14352) ops/sec, 2.32MB/sec (avg: 2.30MB/sec), 713.89 (avg: 462.80) msec latency
Connection error: Connection reset by peer
connection dropped.
connection dropped.
connection dropped.
connection dropped.
```

Are there any settings I'm missing when connecting remotely? 

These are the results when running locally on ubuntu running on AWS:
```
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
[RUN #1 100%,  13 secs]  0 threads:     8000000 ops,  585879 (avg:  586421) ops/sec, 29.19MB/sec (avg: 29.23MB/sec), 13.65 (avg: 13.62) msec latency

4         Threads
100       Connections per thread
20000     Requests per client


ALL STATS
=========================================================================
Type         Ops/sec     Hits/sec   Misses/sec      Latency       KB/sec
-------------------------------------------------------------------------
Sets        60403.67          ---          ---     13.62500     10374.26
Gets       603737.82        33.21    603704.61     13.62300     23520.18
Waits           0.00          ---          ---      0.00000          ---
Totals     664141.49        33.21    603704.61     13.62300     33894.44
```

**Comment by eni9889** [comment] 2020-05-20 22:02
It seems like my issue is related to this: https://github.com/JohnSully/KeyDB/issues/170

**Comment by eni9889** [comment] 2020-05-20 22:59
this is the syslog
```
May 20 22:56:42 ip-172-31-68-75 systemd[1]: keydb-server.service: Main process exited, code=killed, status=11/SEGV
May 20 22:56:42 ip-172-31-68-75 systemd[1]: keydb-server.service: Failed with result 'signal'.
May 20 22:56:42 ip-172-31-68-75 systemd[1]: keydb-server.service: Service hold-off time over, scheduling restart.
May 20 22:56:42 ip-172-31-68-75 systemd[1]: keydb-server.service: Scheduled restart job, restart counter is at 20.
May 20 22:56:42 ip-172-31-68-75 systemd[1]: Stopped Advanced key-value store.
May 20 22:56:42 ip-172-31-68-75 systemd[1]: Starting Advanced key-value store...
May 20 22:56:43 ip-172-31-68-75 systemd[1]: keydb-server.service: Can't open PID file /var/run/keydb/keydb-server.pid (yet?) after start: No such file or directory
May 20 22:56:43 ip-172-31-68-75 systemd[1]: Started Advanced key-value store.
May 20 22:57:10 ip-172-31-68-75 kernel: [ 1301.937915] keydb-pro-serve[6614]: segfault at ffffffffffffffff ip 000055d9395a2a87 sp 00007f9429ff7e40 error 5 in keydb-pro-server[55d93945d000+6f9000]
```

**Comment by JohnSully** [comment] 2020-05-25 06:27
Hi @eni9889 

Do you have the callstack from the keydb log?  To conclusively confirm its a dupe of #170.

**Comment by eni9889** [comment] 2020-05-25 11:58
@JohnSully, unfortunately, I don't and  I ended up having to swap out the db for redis since this was a production system. Everything worked fine in staging/develop but our prod system is dealing with thousands of requests per second and there the keydb server kept dying. It would be difficult for me to reproduce without bringing down our production site.

**Comment by JohnSully** [comment] 2020-05-25 16:30
I understand. Thank you for helping with this and the other bug.

**Comment by eni9889** [comment] 2020-06-03 03:26
I updated to 6.0.8 RC and still go the crash sadly. 

```
Jun  3 03:24:38 ip-172-31-14-254 systemd[1]: keydb-server.service: Main process exited, code=killed, status=6/ABRT
Jun  3 03:24:38 ip-172-31-14-254 systemd[1]: keydb-server.service: Failed with result 'signal'.
Jun  3 03:24:38 ip-172-31-14-254 systemd[1]: keydb-server.service: Service hold-off time over, scheduling restart.
Jun  3 03:24:38 ip-172-31-14-254 systemd[1]: keydb-server.service: Scheduled restart job, restart counter is at 6.
Jun  3 03:24:38 ip-172-31-14-254 systemd[1]: Stopped Advanced key-value store.
Jun  3 03:24:38 ip-172-31-14-254 systemd[1]: Starting Advanced key-value store...
```

**Comment by JohnSully** [comment] 2020-06-06 01:08
Are you using KeyDB Pro in a cluster configuration?

**Comment by christianEQ** [comment] 2021-08-20 18:00
We've done some work on fixing dropped connections recently, and I wasn't able to reproduce this as of the current version, so I'm fairly certain this has been fixed.

**Closed by christianEQ** 2021-08-20 18:00 UTC
