### ISSUE TITLE
Master-slave performance issue when they run in the multithreading mode

### ISSUE THREAD

**Issue by hengku** [EQ-Alpha/KeyDB#246] opened 2020-10-08 16:03 UTC
Hi, I found a master-slave performance issue when they run in the multithreading mode. Below is how I re-produced it (for both 6.0.16 release and 6.0.13 release): 

1)	Started a master (on machine A) with 4 threads
2)	Started a slave (on machine B) of the master above with 4 threads
3)	Run memtier (on machine C) against the master: memtier_benchmark -s <ip> -p <port> -t 50 -c 1 -n 500000 -d 256 --key-minimum=1 --key-maximum=25000000 --ratio 1:0 --key-pattern=P:P --hide-histogram
4)	The QPS was around 165K only; it was around 340K if no slave
5)	The CPU usage of the master during the test was around 400%
6)	The CPU usage of the slave during the test was around 40%
7)	RDB or AOF was not enabled
8)	No disconnection or full sync between the master and slave happened during the test
9)	The read performance is normal as master-only mode: memtier_benchmark -s <ip> -p <port> -t 50 -c 1 -n 500000 -d 256 --key-minimum=1 --key-maximum=25000000 --ratio 0:1 --key-pattern=P:P --hide-histogram

Please let me know if you need more information, thank you!

**Comment by JohnSully** [comment] 2020-10-10 16:46
The problem is related to client lock overhead. I’ve got a local fix, just doing a bit more testing.

**Comment by VivekSainiEQ** [comment] 2021-08-17 22:38
Hi all,

With KeyDB 6.0.16, I get ~320K queries per seconds without replica, ~140K with replica (in line with what you're reporting).
With KeyDB 6.2.0 (the latest version), I also get ~320K queries without a replica, and ~270K with replica.

Seems like the work done with regards to replication between 6.0.16 and 6.2.0 has solved the performance problem, so I'm closing this issue.

**Closed by VivekSainiEQ** 2021-08-17 22:38 UTC
